TrainerProject/TrainerApp/urls.py
from django.conf import settings
from django.urls import path
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path("", views.home, name="home"),
    path("units/<int:id>/", views.unit, name="units"),
    path("courses/<int:id>/", views.course, name="courses"),
    path("departments/", views.department, name="departments"),
    path("documents/<int:id>/", views.document, name="documents"),
    path('contrib/user-login/', views.user_login, name='user-login'),
    path('contrib/user-register/', views.user_register, name='user-register'),
    path('contrib/user-logout/', views.user_logout, name='user-logout'),
    path('contrib/dashboard/', views.dashboard, name='dashboard'),
    path('contrib/courses/<int:id>/', views.user_courses, name='user-courses'),
    path('contrib/units/<int:id>/', views.user_units, name='user-units'),
    path('contrib/documents/<int:id>/', views.user_resources, name='user-documents'),
    path('contrib/add-course/', views.add_course, name='add-course'),
    path('contrib/add-unit/<int:id>/', views.add_unit, name='add-unit'),
    path('contrib/add-document/<int:id>', views.add_document, name='add-document'),
    path('tvet-ai/', views.ai_home, name='tvet-ai'),
    path('learning-plan/', views.selection_view, name='learning-plan'),
    path('session-plan/', views.session_plan, name='session-plan'),
    path('ajax/get-courses/', views.get_courses, name='get_courses'),
    path('ajax/get-units/', views.get_units, name='get_units'),
    path('ajax/get-documents/', views.get_documents, name='get_documents'),
    # path('api/check-stk-status/', views.check_stk_status, name='check-stk-status-api'),
    path("callback/", views.process_stk_callback, name="stk-callback"),
    path('payment-wait/', views.payment_wait, name='payment-wait'),
    path('check-transaction-status/', views.check_transaction_status, name='check-transaction-status'),
    path('contact', views.contact, name='contact'),
    path('ai/forms/', views.upload_form, name='ai'),
    path("results/", views.show_results, name="show_results"),
    
    path("upload-and-start/", views.upload_and_start, name="upload_and_start"),
    path("check-task-status/<str:task_id>/", views.check_task_status, name="check_task_status"),
    path("download/<str:filename>/", views.download_file, name="download_file"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrainerProject/TrainerProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("TrainerApp.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TrainerProject/TrainerApp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Department(models.Model):
    department_name = models.CharField(max_length=100, unique=True)
    department_image = models.ImageField(upload_to='department_images/', blank=True, null=True)

    def __str__(self):
        return self.department_name


class CustomUser(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True, blank=True)
    phone_number = models.IntegerField(null=True, blank=True)
    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.department}"


class Course(models.Model):
    class LevelChoices(models.TextChoices):
        LEVEL_6 = 'L6', 'Level 6'
        LEVEL_5 = 'L5', 'Level 5'
        LEVEL_3 = 'L3', 'Level 3'
        LEVEL_4 = 'L4', 'Level 4'
        
    class CycleChoices(models.TextChoices):
        CYCLE_1 = 'C1', 'Cycle 1'
        CYCLE_2 = 'C2', 'Cycle 2'
        CYCLE_3 = 'C3', 'Cycle 3'
        
    cycle = models.CharField(max_length=2, choices=CycleChoices.choices, default=CycleChoices.CYCLE_1)
    course_code = models.CharField(max_length=10)
    course_name = models.CharField(max_length=100, unique=True)
    course_image = models.ImageField(upload_to='course_images/', blank=True, null=True)
    course_level = models.CharField(max_length=2, choices=LevelChoices.choices, default=LevelChoices.LEVEL_6)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.course_name} {self.course_code}"


class Unit(models.Model):
    class ModuleChoices(models.TextChoices):
        MODULE_1 = 'M1', 'Module 1'
        MODULE_2 = 'M2', 'Module 2'
        MODULE_3 = 'M3', 'Module 3'
        MODULE_4 = 'M4', 'Module 4'
        MODULE_5 = 'M5', 'Module 5'
        MODULE_6 = 'M6', 'Module 6'
        
    class CompetencyChoices(models.TextChoices):
        BASIC = 'BC', 'Basic Competency'
        CORE = 'CR', 'Core Competency'
        COMMON = 'CC', 'Common Competency'

    module = models.CharField(max_length=2, choices=ModuleChoices.choices, default=ModuleChoices.MODULE_1, blank=True, null=True)
    unit_code = models.CharField(max_length=20)
    unit_name = models.CharField(max_length=100)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    competency = models.CharField(max_length=2, choices=CompetencyChoices.choices, default=CompetencyChoices.BASIC , blank=True, null=True)

    def __str__(self):
        return f"{self.unit_name} {self.unit_code}"


class Document(models.Model):
    class DocumentChoices(models.TextChoices):
        OCCUPATIONAL_STANDARDS = 'OS', 'Occupational Standards'
        CURRICULUM = 'CU', 'Curriculum'
        ASSESSMENT_TOOLS = 'AT', 'Assessment Tools'
        LEARNING_PLAN = 'LP', 'Learning Plan'
        WEIGHTING_TOOL = 'WT', 'Weighting Tool'
        OTHER_DOCUMENTS = 'OD', 'Other Documents'

    document_name = models.CharField(max_length=100, unique=True)
    document_file = models.FileField(upload_to='documents/')
    document_type = models.CharField(max_length=2, choices=DocumentChoices.choices,
                                     default=DocumentChoices.OCCUPATIONAL_STANDARDS)
    unit = models.ForeignKey(Unit, on_delete=models.CASCADE)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    uploaded_by = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True, blank=True)
    downloads = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.document_name

class Transactions(models.Model):
    merchant_request_id = models.CharField(max_length=50, null=True, blank=True)
    checkout_request_id = models.CharField(max_length=50, null=True, blank=True)
    result_code = models.IntegerField(null=True, blank=True)
    result_desc = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    transaction_id = models.CharField(max_length=50, null=True, blank=True)
    user_phone_number = models.CharField(max_length=15, null=True, blank=True)
    transaction_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Transaction {self.transaction_id} by {self.user_phone_number}"
    
class TrainingSession(models.Model):
    trainer_name = models.CharField(max_length=100)
    trainer_number = models.CharField(max_length=15)
    number_of_weeks = models.IntegerField(null=True, blank=True)
    number_of_sessions_per_week = models.IntegerField(null=True, blank=True)
    hours_per_session = models.IntegerField(null=True, blank=True)
    department = models.CharField(max_length=100, null=True, blank=True)
    course = models.CharField(max_length=100,null=True, blank=True)
    unit = models.CharField(max_length=100, null=True, blank=True)
    transaction = models.ForeignKey(Transactions, on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.trainer_name} - {self.course}"

TrainerProject/TrainerApp/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit

from .models import Course, CustomUser, Department, Document, Unit

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(widget=forms.PasswordInput)
    
class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = CustomUser
        fields = (
            'profile_picture',
            'username',
            'first_name',
            'last_name',
            'department',
            'email',
            'phone_number',
            'password'
        )
        
class AddCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ('course_name', 'course_code', 'cycle', 'course_level', 'course_image', )
        
class AddUnitForm(forms.ModelForm):
    class Meta:
        model = Unit
        fields = ('unit_name', 'unit_code', 'module', 'competency')
        
class AddDocumentForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = ('document_name', 'document_file', 'document_type')
        
class SelectionForm(forms.Form):
    
    trainer_name = forms.CharField(max_length=100, widget=forms.NumberInput(attrs={'placeholder': 'Enter Your Name'}))
    phone_number = forms.IntegerField(label="Enter Your M-PESA Number", widget=forms.NumberInput(attrs={'placeholder': '254700XXXXXX'}))
    number_weeks = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Number of Weeks for the Term'}))
    number_of_sessions_per_week = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Number of Sessions per Week'}))
    hours_per_session = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder': 'Hours per Session'}))
    
    department = forms.ModelChoiceField(
        queryset=Department.objects.all(),
        empty_label="Select Department",
        widget=forms.Select(attrs={'id': 'id_department'})
    )
    course = forms.ModelChoiceField(
        queryset=Course.objects.none(),
        empty_label="Select Course",
        widget=forms.Select(attrs={'id': 'id_course'})
    )
    unit = forms.ModelChoiceField(
        queryset=Unit.objects.none(),
        empty_label="Select Unit",
        widget=forms.Select(attrs={'id': 'id_unit'})
    )
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-md-3 col-sm-12'
        self.helper.field_class = 'col-md-9 col-sm-12'
        
        self.helper.layout = Layout(
            Row(
                Column('trainer_name', css_class='form-group col-md-6 col-sm-12'),
                Column('phone_number', css_class='form-group col-md-6 col-sm-12'),
            ),
            Row(
                Column('number_weeks', css_class='form-group col-md-6 col-sm-12'),
                Column('number_of_sessions_per_week', css_class='form-group col-md-6 col-sm-12'),
            ),
            Row(
                Column('hours_per_session', css_class='form-group col-md-6 col-sm-12'),
                Column('department', css_class='form-group col-md-4 col-sm-12'), 
            ),
            Row(
                
                Column('course', css_class='form-group col-md-6 col-sm-12'),
                Column('unit', css_class='form-group col-md-6 col-sm-12'),
            ),
            Submit('submit', 'Submit', css_class='btn btn-primary'),
        )
        
        # Handle server-side queryset filtering for form validation (if form is submitted)
        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['course'].queryset = Course.objects.filter(department=department_id).order_by('course_name')
            except (ValueError, TypeError):
                pass
        if 'course' in self.data:
            try:
                course_id = int(self.data.get('course'))
                self.fields['unit'].queryset = Unit.objects.filter(course=course_id).order_by('unit_name')
            except (ValueError, TypeError):
                pass

class MpesaForm(forms.Form):
    mpesa_number = forms.IntegerField(label="Enter your Mpesa Number", widget=forms.NumberInput(attrs={'placeholder': '254700XXXXXX'}))

class UploadFilesForm(forms.Form):
    num_weeks = forms.IntegerField(label="Number of Weeks", widget=forms.NumberInput(attrs={'placeholder': 'e.g., 12'}))
    sessions_per_week = forms.IntegerField(label="Sessions per Week", widget=forms.NumberInput(attrs={'placeholder': 'e.g., 3'}))
    hours_per_session = forms.IntegerField(label="Hours per Session", widget=forms.NumberInput(attrs={'placeholder': 'e.g., 2'}))
    curriculum = forms.FileField(label="Upload Curriculum (PDF)")
    occupational_standard = forms.FileField(label="Upload Occupational Standard (PDF)")

TrainerProject/TrainerApp/templates/back-end/add-course.html
{% extends "back-end/base.html" %}
{% load crispy_forms_tags %}

{% block main_block %}

<div class="container-fluid shadow-sm">
    <h3 class="h3">Add Course</h3>
</div>
{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mt-3">{{ message }}</div>
        {% endfor %}
    {% endif %}

<a href="{% url "user-courses" user.department.id %}">Back To Courses</a>
<div class="container">
    <h3 class="h3 text-center mt-3 mb-3">Add a New Course</h3>
    <p class="text-center mb-3">Fill in the details below to create a new course.</p>
</div>
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Course</button>
    </form>
    
</div>
{% endblock main_block %}

TrainerProject/TrainerApp/templates/back-end/add-document.html
{% extends "back-end/base.html" %}
{% load crispy_forms_tags %}

{% block main_block %}
<div class="container-fluid shadow-sm">
    <h3 class="h3">Add Document for {{ unit.unit_name }}</h3>
    <p class="text-center mb-3">Fill in the details below to create a new document.</p>
</div>
<a href="{% url "user-units" unit.id %}">Back To Units</a>
{% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mt-3">{{ message }}</div>
        {% endfor %}
    {% endif %}
<div class="container">
    <h3 class="h3 text-center mt-3 mb-3">Add a New Document</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Document</button>
    </form>
    
{% endblock main_block %}

TrainerProject/TrainerApp/templates/back-end/add-unit.html
{% extends "back-end/base.html" %}
{% load crispy_forms_tags %}

{% block main_block %}
<div class="container-fluid shadow-sm">
    <h3 class="h3">Add Unit</h3>
    <p class="text-center mb-3">Fill in the details below to create a new unit.</p>
</div>
<div class="container">
    <h3 class="h3 text-center mt-3 mb-3">Add a New Unit</h3>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Add Unit</button>
    </form>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} mt-3">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endblock main_block %}

TrainerProject/TrainerApp/templates/back-end/base.html
<html>
<head>
    <title>TrainerApp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        .sidebar {
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            width: 250px;
            background-color: #eea00fff;
            padding-top: 20px;
        }
        .sidebar .nav-link {
            color: #ffffff;
            padding: 10px 20px;
            transition: background-color 0.3s;
        }
        .sidebar .nav-link:hover {
            background-color: #495057;
        }
        .content {
            margin-left: 250px;
            padding: 20px;
        }
    </style>
</head>
<body> 
    <div class="sidebar">
        <h3 class="text-white text-center mb-4">Tvet Tusome</h3>
        {% if user.is_authenticated %}
            <img src={{ user.profile_picture.url }} alt="User Profile" class="rounded-circle mx-auto d-block" height='50px' width='50px'>
            <p class="text-white text-center mb-2">{{ user.username }}</p>
            <p class="text-white text-center mb-2">{{ user.email }}</p>
            <p class="text-white text-center mb-2">{{ user.department }}</p>
        {% endif %}
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">Dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user-courses' user.department.id %}">Courses</a>
            </li>
            {% comment %} <li class="nav-item">
                <a class="nav-link" href="#">Cycle 2</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Cycle 3</a>
            </li> {% endcomment %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user-logout' %}">Logout</a>
            </li>
        </ul>
    </div>
    <div class="content">
        {% block main_block%}

        {% endblock%}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

TrainerProject/TrainerApp/templates/back-end/dashboard.html
{% extends 'back-end/base.html' %}

{%block main_block%}
<h3 class="text-center">Welcome to the Dashboard</h3>
{% endblock %}

TrainerProject/TrainerApp/templates/back-end/login.html
{% load crispy_forms_tags %}
<html>
<head>
    <title>TrainerApp</title>
    {% comment %} <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-12 col-lg-6">
                <div class="logo">
                    {% comment %} <img src="{% static 'images/logo.png' %}" alt="TrainerApp Logo" class="img-fluid">  {% endcomment %}
                <div>
            </div>
            <div class="col-md-6 col-sm-12 col-lg-6">
                <h2>Login</h2>
                <form method="post" action="">
                    {% csrf_token %}
                    {{ login_form|crispy }}
                    <button type="submit" class="btn btn-primary">Login</button>
                </form>
                {% if messages %}
                    <div class="alert alert-danger mt-3">{{ messages }}</div>
                {% endif %}
                <p class="mt-3">Don't have an account? <a href="{% url 'user-register' %}">Register here</a></p>
                <p>Forgot your password? <a href="#">Reset it here</a></p>
                <p>Back to <a href="#">Home</a></p>
            </div>
    </div>
    <footer class="text-center mt-4">
        <p>&copy; 2023 TrainerApp. All rights reserved.</p>
    </footer>
</body>
</html>

TrainerProject/TrainerApp/templates/back-end/register.html
{% load crispy_forms_tags %}
<html>
    <head>
        <title>TrainerApp - Register</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
    <body class="container">
        <div class="row">
            <div class="col-md-6 ">
                <h1>Register</h1>
            </div>
            <div class="col-md-6">
                <p>Welcome to TrainerApp! Please fill out the form below to create a new account.</p>

                <form method="post" action="">
                    {% csrf_token %}
                    {{ register_form|crispy }}
                    <button type="submit" class="btn btn-success btn-sm">Register</button>
                </form>
                <p>Already have an account? <a href="{% url 'user-login' %}">Login here</a></p>
                {% if messages %}
                <ul>
                    {% for message in messages %}
                    <li>{{ message }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
            </div>
        </div>
    </body>
</html>

TrainerProject/TrainerApp/templates/back-end/user-resources.html
{% extends "back-end/base.html" %}

{% block main_block %}
<div class="container-fluid shadow-sm">
    <h3 class="h3">Unit Resources</h3>
    <p class="text-center mb-3">Resources for <strong>{{ unit.unit_name }}</strong> <br> Unit Code <strong>{{ unit.unit_code }}</strong></p>
</div>
    <div class="container d-flex justify-content-end mb-3">
        <a href="{% url 'user-units' unit.id %}" class="text-end btn btn-sm btn-outline-warning rounded">BACK TO UNITS</a>
        <a href="{% url 'add-document' unit.id %}" class="text-end btn btn-sm btn-outline-warning rounded">ADD DOCUMENT</a>
    </div>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} mt-3">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% if documents %}
            <div class="container">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Document Name</th>
                            <th>Type</th>
                            <th>Uploaded By</th>
                            <th>View Document</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for document in documents %}
                        <tr>
                            <td>{{ document.document_name }}</td>
                            <td>{{ document.get_document_type_display }}</td>
                            <td>{{ document.uploaded_by.username }}</td>
                            <td>
                                <a href="{{ document.document_file.url }}" class="btn btn-sm btn-primary" target="_blank">View</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </div>
        {% else %}
            <p>No documents available.</p>
        {% endif %}
    </div>
{% endblock %}  

TrainerProject/TrainerApp/templates/back-end/user-units.html
{% extends "back-end/base.html" %}

{% block main_block %}
<div class="container-fluid shadow-sm">
    <h3 class="h3">User Units</h3>
</div>
<div class="container">
    <h3 class="h3 text-center mt-3 mb-3">{{ course }}</h3>
</div>
<div class="container">
    <a href="{% url 'add-unit' course.id %}" class="btn btn-sm btn-outline-primary mb-3">ADD UNIT</a>
    <a href="{% url 'user-courses' user.department.id %}" class="btn btn-sm btn-outline-primary mb-3">BACK TO COURSES</a>
</div>

<ul class="nav nav-tabs nav-justified">
  <li class="nav-item">
    <a class="nav-link active" data-bs-toggle="tab" href="#basic">Basic Units</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#core">Common Units</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-bs-toggle="tab" href="#common">Core Units</a>
  </li>
</ul>

<div class="container tab-content">
    <div class="tab-pane container active" id="basic">
        {% if units %}
        {% for unit in units %}
            {% if unit.competency == "BC" %}
            <div class="row justify-content-center mb-4 bg-white p-3 rounded">
                <div class="col-md-2 col-sm-12">
                    <div class="text-center h1">📋</div>
                </div>
                <div class="col-md-8 col-sm-12 align-content-around">
                    <div class="row">
                        <div class="col-12">
                            <p class="text-center h3">{{ unit.unit_name}}</p>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-12">
                            <p class="text-center">{{ unit.unit_code }}</p>
                        </div>
                        <div class="col-md-6 col-sm-12 text-center">
                            <a href="{% url 'user-documents' unit.id %}" class="btn btn-info">View Documents</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        {% else %}
        <div class="alert alert-warning text-center" role="alert">
            <strong>No units found!</strong>
            <a href="{% url "add-unit" course.id %}" class="alert-link btn btn-info">ADD UNIT</a>
        </div>
        {% endif %}
    </div>

    <div class="tab-pane container fade" id="common">
        {% if units %}
        {% for unit in units %}
            {% if unit.competency == "cC" %}
            <div class="row justify-content-center mb-4 bg-white p-3 rounded">
                <div class="col-md-2 col-sm-12">
                    <div class="text-center h1">📋</div>
                </div>
                <div class="col-md-8 col-sm-12 align-content-around">
                    <div class="row">
                        <div class="col-12">
                            <p class="text-center h3">{{ unit.unit_name}}</p>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-12">
                            <p class="text-center">{{ unit.unit_code }}</p>
                        </div>
                        <div class="col-md-6 col-sm-12 text-center">
                            <a href="{% url 'user-documents' unit.id %}" class="btn btn-info">View Documents</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        {% else %}
        <div class="alert alert-warning text-center" role="alert">
            <strong>No units found!</strong>
            <a href="{% url "add-unit" course.id %}" class="alert-link btn btn-info">ADD UNIT</a>
        </div>
        {% endif %}
    </div>

    <div class="tab-pane container fade" id="core">
        {% if units %}
        {% for unit in units %}
            {% if unit.competency == "CR" %}
            <div class="row justify-content-center mb-4 bg-white p-3 rounded">
                <div class="col-md-2 col-sm-12">
                    <div class="text-center h1">📋</div>
                </div>
                <div class="col-md-8 col-sm-12 align-content-around">
                    <div class="row">
                        <div class="col-12">
                            <p class="text-center h3">{{ unit.unit_name}}</p>
                        </div>
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6 col-sm-12">
                            <p class="text-center">{{ unit.unit_code }}</p>
                        </div>
                        <div class="col-md-6 col-sm-12 text-center">
                            <a href="{% url 'user-documents' unit.id %}" class="btn btn-info">View Documents</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
        {% endfor %}
        {% else %}
        <div class="alert alert-warning text-center" role="alert">
            <strong>No units found!</strong>
            <a href="{% url "add-unit" course.id %}" class="alert-link btn btn-info">ADD UNIT</a>
        </div>
        {% endif %}
    </div>
    
</div>
{% endblock main_block %}